### ISSUE TITLE
getVulkanVersion: invalid literal for int()

### ISSUE THREAD

**Issue by cweiske** [arunsivaramanneo/GPU-Viewer#60]
When starting gpu-viewer an error is shown in the terminal:
```
$ gpu-viewer 
Traceback (most recent call last):
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 695, in radcall
    Devices(text)
  File "/usr/share/gpu-viewer/Files/VulkanViewer.py", line 104, in Devices
    valueRHS[i] = getVulkanVersion(valueRHS[i])
  File "/usr/share/gpu-viewer/Files/Common.py", line 173, in getVulkanVersion
    majorVersion = int(value) >> 22
ValueError: invalid literal for int() with base 10: '1.3.224 \n'
```

The application nevertheless starts.

Version: gpu-viewer 1.37f2-1 from Ubuntu PPA, running on Ubuntu 20.04 LTS.
(I know that version 2.12 exists, but the PPA does not offer a newer version, and installing the .deb from releases download has gtk4 dependency problems.)

Related errors from 2019: #21, #24.

**Comment by tinywrkb** [comment]
Same here, though haven't looked into this, as I didn't had time for it. I
did held back the Flathub update due to the regression, so users shouldn't
be affected.

**Comment by arunsivaramanneo** [comment]
Hi thanks for raising this issue... Ubuntu 22.04 has vulkan tools version 1.2.131 in its repository, I have not been able to bundle Vulkan tools ,, gpu-viewer v1.37 will only work with the vulkan tools version 1.2.131 or lower. can you try version 1.40 https://github.com/arunsivaramanneo/GPU-Viewer/releases/download/v1.40/gpu-viewer_1.40J1-1_amd64.deb and let me know if you still see the issue. V1.40 should work fine with Vulkan Tools version 1.3.212 and higher

@tinywrkb for Flatpak is it happening with the latest version of vulkan Tools and gpu-viewer 2.12?

I couldn't release v 1.40 or above to Ubuntu 20.04 due to below reasons
1) I couldn't package latest version of Vulkan Tools for 20.04
2) Ubuntu official repository they don't update Vulkan Tools after Release so 20.04 is stuck with 1.2.131. I know users can clone Vulkan Tools but they will also need to clone gpu-viewer and install.
3) gpu-viewer v2.0 above need Gtk 4 which i am not sure if ubuntu 20.04 repositories provide. (I will try to install the 20.04 and see if the v2.0 work on 20,04 , i really get a chance to test it as i hardly have hardware to install different version of Ubuntu, leave with me i will give an update soon)

**Comment by tinywrkb** [comment]
The Flatpak bundles Vulkan Tools 1.3.236.
Now I'm actually next to my machine, I can see that the issue is different, so I guess this warrants a new ticket.

```
Traceback (most recent call last):
  File "/app/share/gpu-viewer/Files/VulkanViewer.py", line 961, in radcall
    Instance()
  File "/app/share/gpu-viewer/Files/VulkanViewer.py", line 712, in Instance
    iter = LayerTab_Store.append(None,[layer_names[i], layer_vulkan_version[i], layer_version[i],
IndexError: list index out of range
```

I will try to look at this again tomorrow.

**Comment by arunsivaramanneo** [comment]
i just had a look and its an issue .. i will look into it ... thanks

**Comment by tinywrkb** [comment]
v2.13 look good, and now published on Flathub.

**Comment by arunsivaramanneo** [comment]
> v2.13 look good, and now published on Flathub.

thanks a lot

**Comment by arunsivaramanneo** [comment]
> v2.13 look good, and now published on Flathub.

does it take time to be available on Flathub, i still see it as v2.02

**Comment by tinywrkb** [comment]
Not sure what went wrong. The publishing step was successful, but the build wasn't added to the Flathub's repo.  That's a new for me, as usually a few minutes after the publishing step the updated build is added to the stable branch, and it never failed to get in there.  
I initiated today a manual rebuild, but it seems like ATM the CI is failing to publish new builds.  
I will give it another shot tomorrow after work.

**Comment by arunsivaramanneo** [comment]
Thanks a lot, i can see that now 😃👍
